/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef IDataFrameService_TYPES_H
#define IDataFrameService_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "IDriverException_types.h"
#include "../ISource_types.h"


namespace ignis { namespace rpc { namespace driver {

class IDataFrameId;


class IDataFrameId : public virtual ::apache::thrift::TBase {
 public:

  IDataFrameId(const IDataFrameId&);
  IDataFrameId& operator=(const IDataFrameId&);
  IDataFrameId() : cluster(0), worker(0), dataFrame(0) {
  }

  virtual ~IDataFrameId() noexcept;
  int64_t cluster;
  int64_t worker;
  int64_t dataFrame;

  void __set_cluster(const int64_t val);

  void __set_worker(const int64_t val);

  void __set_dataFrame(const int64_t val);

  bool operator == (const IDataFrameId & rhs) const
  {
    if (!(cluster == rhs.cluster))
      return false;
    if (!(worker == rhs.worker))
      return false;
    if (!(dataFrame == rhs.dataFrame))
      return false;
    return true;
  }
  bool operator != (const IDataFrameId &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const IDataFrameId & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(IDataFrameId &a, IDataFrameId &b);

std::ostream& operator<<(std::ostream& out, const IDataFrameId& obj);

}}} // namespace

#endif
