/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "IDriverException_constants.h"

namespace ignis { namespace rpc { namespace driver {

const IDriverExceptionConstants g_IDriverException_constants;

IDriverExceptionConstants::IDriverExceptionConstants() {
}

}}} // namespace

