/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef IPropertiesService_CONSTANTS_H
#define IPropertiesService_CONSTANTS_H

#include "IPropertiesService_types.h"

namespace ignis { namespace rpc { namespace driver {

class IPropertiesServiceConstants {
 public:
  IPropertiesServiceConstants();

};

extern const IPropertiesServiceConstants g_IPropertiesService_constants;

}}} // namespace

#endif
