/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef IDataService_CONSTANTS_H
#define IDataService_CONSTANTS_H

#include "IDataService_types.h"

namespace ignis { namespace rpc { namespace driver {

class IDataServiceConstants {
 public:
  IDataServiceConstants();

};

extern const IDataServiceConstants g_IDataService_constants;

}}} // namespace

#endif
