/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ISource_CONSTANTS_H
#define ISource_CONSTANTS_H

#include "ISource_types.h"

namespace ignis { namespace rpc {

class ISourceConstants {
 public:
  ISourceConstants();

};

extern const ISourceConstants g_ISource_constants;

}} // namespace

#endif
