/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ICommModule_CONSTANTS_H
#define ICommModule_CONSTANTS_H

#include "ICommModule_types.h"

namespace ignis { namespace rpc { namespace executor {

class ICommModuleConstants {
 public:
  ICommModuleConstants();

};

extern const ICommModuleConstants g_ICommModule_constants;

}}} // namespace

#endif
