/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "IKeysModule_constants.h"

namespace ignis { namespace rpc { namespace executor {

const IKeysModuleConstants g_IKeysModule_constants;

IKeysModuleConstants::IKeysModuleConstants() {
}

}}} // namespace

