/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "IServerModule_constants.h"

namespace ignis { namespace rpc { namespace executor {

const IServerModuleConstants g_IServerModule_constants;

IServerModuleConstants::IServerModuleConstants() {
}

}}} // namespace

